import type { ChecklistSection } from './types'

export const FE_SECTIONS: ChecklistSection[] = [
  { id: 'fe-biz', icon: '🏪', title: 'product & business', items: [
    { id: '1', l: 'Business model defined', tag: 'both', s: 'SaaS / marketplace / B2B / B2C / API / open-core' },
    { id: '2', l: 'Framework applied', tag: 'both', s: 'Lean Canvas, BMC, JTBD, Blue Ocean' },
    { id: '3', l: 'ICP & persona defined', tag: 'both' },
    { id: '4', l: 'Competitive landscape mapped', tag: 'both' },
    { id: '5', l: 'Revenue model & pricing', tag: 'both' },
    { id: '6', l: 'GTM motion defined', tag: 'both' },
    { id: '7', l: 'First vertical slice defined', tag: 'new', s: 'One E2E flow proving full stack' },
    { id: '8', l: 'Demo-day acceptance criteria', tag: 'both' },
  ]},
  { id: 'fe-prd', icon: '📄', title: 'PRD & requirements', items: [
    { id: '1', l: 'Problem statement written', tag: 'fe', auto: 'has_readme', autoSignal: 'README.md found' },
    { id: '2', l: 'Success metrics & KPIs defined', tag: 'fe' },
    { id: '3', l: 'User stories / JTBD', tag: 'fe' },
    { id: '4', l: 'Feature scope: MVP → V1 → V2', tag: 'fe' },
    { id: '5', l: 'Non-functional requirements', tag: 'fe' },
    { id: '6', l: 'Dogfooding plan', tag: 'fe', autoWarn: 'has_changelog', autoSignal: 'CHANGELOG detected — confirm dogfooding section exists' },
    { id: '7', l: 'Sprint plan & milestone cadence', tag: 'fe' },
  ]},
  { id: 'fe-ux', icon: '🎨', title: 'UX & design', items: [
    { id: '1', l: 'User flow diagram', tag: 'fe' },
    { id: '2', l: 'Wireframes', tag: 'fe' },
    { id: '3', l: 'Hi-fi mockups / design system', tag: 'fe' },
    { id: '4', l: 'Component library / design tokens', tag: 'fe' },
    { id: '5', l: 'Empty, loading, and error states', tag: 'fe' },
    { id: '6', l: 'Responsive breakpoints defined', tag: 'fe' },
    { id: '7', l: 'Accessibility audit (WCAG 2.1 AA)', tag: 'fe', autoWarn: 'has_lighthouse_ci', autoSignal: 'Lighthouse CI detected — verify accessibility score ≥90' },
    { id: '8', l: 'Interaction feedback spec', tag: 'new' },
    { id: '9', l: 'PWA manifest + service worker', tag: 'new', auto: 'has_pwa', autoSignal: 'manifest.json + service worker detected' },
  ]},
  { id: 'fe-build', icon: '💻', title: 'frontend build', items: [
    { id: '1', l: 'Tech stack locked', tag: 'fe', auto: 'has_package_json', autoSignal: 'package.json detected' },
    { id: '2', l: 'Monorepo vs polyrepo decision', tag: 'fe', auto: 'has_monorepo', autoSignal: 'Workspace config detected' },
    { id: '3', l: 'Feature flags / toggles', tag: 'fe' },
    { id: '4', l: 'Error boundary & fallback UI', tag: 'fe' },
    { id: '5', l: 'Performance budget (Core Web Vitals)', tag: 'fe', auto: 'has_lighthouse_ci', autoSignal: 'Lighthouse CI config detected' },
    { id: '6', l: 'API integration layer abstracted', tag: 'fe' },
    { id: '7', l: 'Environment variables configured', tag: 'fe', auto: 'has_env_example', autoSignal: '.env.example detected' },
    { id: '8', l: 'Module-to-module data linkage', tag: 'new' },
  ]},
  { id: 'fe-dep', icon: '🚀', title: 'frontend deployment', items: [
    { id: '1', l: 'All-in-one platform evaluated', tag: 'aio', auto: 'has_railway', autoSignal: 'railway.toml detected' },
    { id: '2', l: 'Deployment platform selected', tag: 'dep', auto: 'has_deploy_config', autoSignal: 'Deploy config detected' },
    { id: '3', l: 'Production build passes locally', tag: 'fe' },
    { id: '4', l: 'Env vars set in platform', tag: 'dep', auto: 'has_env_example', autoSignal: '.env.example present' },
    { id: '5', l: 'Custom domain configured', tag: 'dep' },
    { id: '6', l: 'HTTPS / SSL active', tag: 'dep', autoWarn: 'has_deploy_config', autoSignal: 'Deploy platform detected — verify HTTPS is enabled' },
    { id: '7', l: 'CI/CD auto-deploy on push', tag: 'dep', auto: 'has_cicd', autoSignal: '.github/workflows/ detected' },
    { id: '8', l: 'Preview / staging URL tested', tag: 'dep', autoWarn: 'has_cicd', autoSignal: 'CI detected — verify preview deploys are enabled' },
    { id: '9', l: 'Lighthouse audit passed', tag: 'fe', auto: 'has_lighthouse_ci', autoSignal: 'Lighthouse CI step detected' },
    { id: '10', l: 'Live URL + dashboard URL recorded', tag: 'dep' },
  ]},
  { id: 'fe-test', icon: '🧪', title: 'frontend testing', items: [
    { id: '1', l: 'E2E tests (Playwright / Cypress)', tag: 'test', auto: 'has_e2e', autoSignal: 'Playwright or Cypress config detected' },
    { id: '2', l: 'Visual regression tests', tag: 'test' },
    { id: '3', l: 'Accessibility test (axe / Lighthouse)', tag: 'test', autoWarn: 'has_lighthouse_ci', autoSignal: 'Lighthouse CI detected — verify axe step included' },
    { id: '4', l: 'Cross-browser smoke test', tag: 'test', autoWarn: 'has_e2e', autoSignal: 'E2E framework detected — confirm cross-browser config' },
    { id: '5', l: 'API error state coverage', tag: 'test' },
    { id: '6', l: 'Dogfooding session completed', tag: 'fe' },
  ]},
  { id: 'fe-launch', icon: '🎉', title: 'frontend launch', items: [
    { id: '1', l: 'Soft launch / beta group defined', tag: 'fe' },
    { id: '2', l: 'Analytics & event tracking live', tag: 'fe' },
    { id: '3', l: 'Feedback capture mechanism', tag: 'fe' },
    { id: '4', l: 'Rollback plan documented', tag: 'fe', auto: 'has_deploy_config', autoSignal: 'Deploy platform config found — one-click rollback available' },
    { id: '5', l: 'Post-launch retro scheduled', tag: 'fe' },
  ]},
]

export const BE_SECTIONS: ChecklistSection[] = [
  { id: 'be-arch', icon: '🕸️', title: 'architecture & data', items: [
    { id: '1', l: 'System architecture diagram', tag: 'be' },
    { id: '2', l: 'Database schema design', tag: 'be', auto: 'has_db_schema', autoSignal: 'Schema file detected (prisma / alembic / migrations)' },
    { id: '3', l: 'Data layer architecture', tag: 'be' },
    { id: '4', l: 'Derived data independent from signals', tag: 'new' },
    { id: '5', l: 'Caching strategy', tag: 'be' },
    { id: '6', l: 'Auth & authorization model', tag: 'be', autoWarn: 'has_auth_file', autoSignal: 'Auth file detected — verify RBAC/RLS is configured' },
    { id: '7', l: 'Observability stack', tag: 'new', auto: 'has_otel', autoSignal: 'OpenTelemetry / Langfuse detected' },
    { id: '8', l: 'LLM tracing spans defined', tag: 'new' },
    { id: '9', l: 'Module-to-module data linkage', tag: 'new' },
  ]},
  { id: 'be-api', icon: '🔌', title: 'API & integrations', items: [
    { id: '1', l: 'API contract agreed before code', tag: 'new', auto: 'has_openapi', autoSignal: 'openapi.yaml / swagger.json detected', autoWarn: 'has_api_routes' },
    { id: '2', l: 'API design pattern selected', tag: 'be', autoWarn: 'has_package_json', autoSignal: 'package.json found — check for tRPC/GraphQL/REST dep' },
    { id: '3', l: 'Third-party contracts documented', tag: 'be' },
    { id: '4', l: 'Webhook design', tag: 'be' },
    { id: '5', l: 'API versioning strategy', tag: 'be', autoWarn: 'has_api_routes', autoSignal: 'API routes detected — define versioning strategy' },
    { id: '6', l: 'Business rules at data layer', tag: 'new' },
    { id: '7', l: 'CORS configured for frontend origin', tag: 'be', auto: 'has_cors', autoSignal: 'CORS config detected' },
  ]},
  { id: 'be-llm', icon: '🧠', title: 'LLM integration', items: [
    { id: '1', l: 'LLM provider / router selected', tag: 'be', auto: 'has_openrouter', autoSignal: 'OpenRouter or LiteLLM dependency detected' },
    { id: '2', l: 'Model selection per task type', tag: 'be' },
    { id: '3', l: 'Prompt architecture', tag: 'be', auto: 'has_prompts', autoSignal: 'prompts/ directory or system prompt files detected' },
    { id: '4', l: 'Context window management', tag: 'be' },
    { id: '5', l: 'RAG pipeline (if applicable)', tag: 'be', auto: 'has_vector_db', autoSignal: 'Vector DB dependency detected' },
    { id: '6', l: 'Hallucination & guardrail strategy', tag: 'be' },
    { id: '7', l: 'Token cost estimate & budget', tag: 'be' },
    { id: '8', l: 'Eval framework', tag: 'be', auto: 'has_evals', autoSignal: 'evals/ or golden dataset directory detected' },
    { id: '9', l: 'LLM observability instrumented', tag: 'new', auto: 'has_otel', autoSignal: 'OTel / Langfuse dependency found' },
  ]},
  { id: 'be-agent', icon: '🤖', title: 'agent architecture', items: [
    { id: '1', l: 'Agent pattern selected', tag: 'be' },
    { id: '2', l: 'Tool / function schema defined', tag: 'be', auto: 'has_tools', autoSignal: 'tools/ or agents/ directory detected' },
    { id: '3', l: 'Discernment & routing logic', tag: 'be' },
    { id: '4', l: 'Memory layer decision', tag: 'be', auto: 'has_memory', autoSignal: 'Honcho / memory backend detected' },
    { id: '5', l: 'MCP server design & tool scope', tag: 'be', auto: 'has_mcp', autoSignal: 'MCP config detected' },
    { id: '6', l: 'Human-in-the-loop checkpoints', tag: 'be' },
    { id: '7', l: 'Agent failure & retry logic', tag: 'be' },
    { id: '8', l: 'Deterministic scoring outside LLM', tag: 'new' },
    { id: '9', l: 'Vendor adapter layer', tag: 'new', auto: 'has_adapter', autoSignal: 'Adapter pattern file detected' },
    { id: '10', l: 'Reusable agent scripts exported', tag: 'new', auto: 'has_scripts', autoSignal: 'scripts/ or agents/ with .py files detected' },
  ]},
  { id: 'be-build', icon: '⚙️', title: 'backend build & infra', items: [
    { id: '1', l: 'Tech stack locked', tag: 'be', auto: 'has_backend_deps', autoSignal: 'Backend manifest detected (requirements.txt / go.mod)' },
    { id: '2', l: 'Monorepo vs polyrepo', tag: 'be', auto: 'has_monorepo', autoSignal: 'Workspace config detected' },
    { id: '3', l: 'Feature flags / toggles', tag: 'be' },
    { id: '4', l: 'Environment parity (dev/staging/prod)', tag: 'be', auto: 'has_docker', autoSignal: 'docker-compose.yml detected' },
    { id: '5', l: 'Connection pool configured', tag: 'be' },
    { id: '6', l: 'Background jobs / cron strategy', tag: 'be', auto: 'has_railway', autoSignal: 'railway.toml detected' },
    { id: '7', l: 'Developer onboarding — time-to-first-run', tag: 'new', auto: 'has_readme', autoSignal: 'README.md detected — verify quickstart exists' },
    { id: '8', l: 'Error handling & structured logging', tag: 'be' },
  ]},
  { id: 'be-db', icon: '🗄️', title: 'database & migrations', items: [
    { id: '1', l: 'Database provisioned', tag: 'be', auto: 'has_db_schema', autoSignal: 'Schema / ORM config detected' },
    { id: '2', l: 'Migration strategy defined', tag: 'be', auto: 'has_migrations', autoSignal: 'migrations/ or alembic/ directory detected' },
    { id: '3', l: 'Migration head mismatches resolved', tag: 'new', autoWarn: 'has_migrations', autoSignal: 'Migrations detected — verify no orphaned heads' },
    { id: '4', l: 'Seed data / fixtures versioned', tag: 'be', auto: 'has_seeds', autoSignal: 'seed.sql / seeds/ / fixtures/ detected' },
    { id: '5', l: 'Backup & restore tested', tag: 'be' },
    { id: '6', l: 'Index performance verified', tag: 'be' },
    { id: '7', l: 'Row-level security configured', tag: 'be', auto: 'has_supabase', autoSignal: 'Supabase config detected — verify RLS policies' },
  ]},
  { id: 'be-dep', icon: '🖥️', title: 'backend deployment', items: [
    { id: '1', l: 'All-in-one platform evaluated', tag: 'aio', auto: 'has_railway', autoSignal: 'railway.toml detected' },
    { id: '2', l: 'Deployment platform selected', tag: 'dep', auto: 'has_deploy_config', autoSignal: 'Deploy config detected' },
    { id: '3', l: 'Env vars in platform vault', tag: 'dep', auto: 'has_env_example', autoSignal: '.env.example found' },
    { id: '4', l: 'CI/CD auto-deploy on push', tag: 'dep', auto: 'has_cicd', autoSignal: '.github/workflows/ detected' },
    { id: '5', l: 'Health check endpoint live', tag: 'be', auto: 'has_health', autoSignal: 'Health check route detected' },
    { id: '6', l: 'Rollback plan — one command', tag: 'be', auto: 'has_deploy_config', autoSignal: 'Platform config with versioned deploys found' },
    { id: '7', l: 'Backend live URL + dashboard recorded', tag: 'dep' },
  ]},
  { id: 'be-test', icon: '🧪', title: 'backend testing', items: [
    { id: '1', l: 'Unit tests — core business logic', tag: 'test', auto: 'has_unit_tests', autoSignal: 'tests/ or __tests__/ directory detected' },
    { id: '2', l: 'Integration tests', tag: 'test', autoWarn: 'has_unit_tests', autoSignal: 'Test directory found — verify integration tests exist' },
    { id: '3', l: 'API contract test', tag: 'test' },
    { id: '4', l: 'Status fields verified before automation', tag: 'new' },
    { id: '5', l: 'Load & stress test', tag: 'test' },
    { id: '6', l: 'Security scan (OWASP top 10)', tag: 'test', auto: 'has_security_scan', autoSignal: 'Security scanner detected in CI' },
    { id: '7', l: 'LLM eval regression', tag: 'be', auto: 'has_evals', autoSignal: 'Eval directory detected' },
  ]},
  { id: 'be-compliance', icon: '🛡️', title: 'compliance & IP', items: [
    { id: '1', l: 'OSS license audit', tag: 'new', auto: 'has_license_check', autoSignal: 'license-checker detected in CI' },
    { id: '2', l: 'Vendor lock-in risk assessed', tag: 'new' },
    { id: '3', l: 'Copyright notice', tag: 'new', auto: 'has_license', autoSignal: 'LICENSE file detected' },
    { id: '4', l: 'Data privacy compliance reviewed', tag: 'new' },
    { id: '5', l: 'Third-party data terms reviewed', tag: 'new' },
    { id: '6', l: 'Adapter layer prevents lock-in', tag: 'new', auto: 'has_adapter', autoSignal: 'Adapter pattern file detected' },
  ]},
]

export const ALL_SECTIONS = [...FE_SECTIONS, ...BE_SECTIONS]

export const TAG_COLORS: Record<string, string> = {
  fe: 'bg-violet-500/10 text-violet-400',
  be: 'bg-emerald-500/10 text-emerald-400',
  both: 'bg-blue-500/10 text-blue-400',
  test: 'bg-red-500/10 text-red-400',
  dep: 'bg-amber-500/10 text-amber-400',
  aio: 'bg-teal-500/10 text-teal-400',
  new: 'bg-pink-500/10 text-pink-400',
  custom: 'bg-stone-500/10 text-stone-400',
}
