import { auth } from '@/lib/auth'
import sql from '@/lib/db'
import { NextResponse } from 'next/server'

async function processCreatePR(
  payload: Record<string, unknown>,
  accessToken: string
): Promise<void> {
  const { repo, title, filename, content } = payload as {
    repo: string
    title: string
    filename: string
    content: string
  }

  const [owner, repoName] = (repo as string).split('/')
  const ghHeaders = {
    Authorization: `Bearer ${accessToken}`,
    Accept: 'application/vnd.github+json',
    'Content-Type': 'application/json',
  }

  // 1. Resolve default branch
  const repoRes = await fetch(`https://api.github.com/repos/${owner}/${repoName}`, { headers: ghHeaders })
  if (!repoRes.ok) throw new Error(`Could not fetch repo info: ${repoRes.status}`)
  const repoData = await repoRes.json()
  const defaultBranch: string = repoData.default_branch ?? 'main'

  // 2. Get default branch SHA
  const refRes = await fetch(
    `https://api.github.com/repos/${owner}/${repoName}/git/ref/heads/${defaultBranch}`,
    { headers: ghHeaders }
  )
  if (!refRes.ok) throw new Error(`Could not get branch ref: ${refRes.status}`)
  const refData = await refRes.json()
  const baseSha: string = refData.object.sha

  // 3. Create a unique branch and commit the file via Contents API
  const branch = `build-cc/script-${Date.now()}`
  const filePath = `scripts/${filename}`
  const fileRes = await fetch(
    `https://api.github.com/repos/${owner}/${repoName}/contents/${filePath}`,
    {
      method: 'PUT',
      headers: ghHeaders,
      body: JSON.stringify({
        message: `chore: add generated script ${filename}`,
        content: Buffer.from(content).toString('base64'),
        branch,
        // GitHub auto-creates the branch from baseSha when it doesn't exist
        // by using the sha field on a new branch create
      }),
    }
  )

  // If the branch doesn't exist yet we need to create it first, then commit
  if (!fileRes.ok) {
    const fileErr = await fileRes.json().catch(() => ({}))
    // Branch doesn't exist — create it then retry the file commit
    if (fileRes.status === 422 || fileRes.status === 404) {
      const branchRes = await fetch(
        `https://api.github.com/repos/${owner}/${repoName}/git/refs`,
        {
          method: 'POST',
          headers: ghHeaders,
          body: JSON.stringify({ ref: `refs/heads/${branch}`, sha: baseSha }),
        }
      )
      if (!branchRes.ok) {
        const branchErr = await branchRes.json().catch(() => ({}))
        throw new Error((branchErr as { message?: string }).message ?? `Branch create failed ${branchRes.status}`)
      }
      const retryRes = await fetch(
        `https://api.github.com/repos/${owner}/${repoName}/contents/${filePath}`,
        {
          method: 'PUT',
          headers: ghHeaders,
          body: JSON.stringify({
            message: `chore: add generated script ${filename}`,
            content: Buffer.from(content).toString('base64'),
            branch,
          }),
        }
      )
      if (!retryRes.ok) {
        const retryErr = await retryRes.json().catch(() => ({}))
        throw new Error((retryErr as { message?: string }).message ?? `File commit failed ${retryRes.status}`)
      }
    } else {
      throw new Error((fileErr as { message?: string }).message ?? `File commit failed ${fileRes.status}`)
    }
  }

  // 4. Open a PR
  const prRes = await fetch(`https://api.github.com/repos/${owner}/${repoName}/pulls`, {
    method: 'POST',
    headers: ghHeaders,
    body: JSON.stringify({
      title,
      body: `Generated by [build.cc](https://build.cc) script generator.\n\nFile: \`${filePath}\``,
      head: branch,
      base: defaultBranch,
    }),
  })

  if (!prRes.ok) {
    const prErr = await prRes.json().catch(() => ({}))
    throw new Error((prErr as { message?: string }).message ?? `PR creation failed ${prRes.status}`)
  }
}

export async function POST() {
  const session = await auth()
  if (!session?.user?.id) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

  const [account] = await sql`
    select access_token from accounts
    where "userId" = ${session.user.id} and provider = 'github'
    order by id desc limit 1
  `

  if (!account?.access_token) {
    return NextResponse.json({ error: 'GitHub token not found' }, { status: 400 })
  }

  const rows = await sql`
    select id, mutation_type, payload
    from sync_queue
    where user_id = ${session.user.id}
      and status = 'queued'
    order by created_at asc
    limit 10
  `

  let processed = 0
  let failed = 0

  for (const row of rows) {
    try {
      await sql`
        update sync_queue set status = 'processing', updated_at = now()
        where id = ${row.id}
      `

      if (row.mutation_type === 'create_pr') {
        await processCreatePR(row.payload as Record<string, unknown>, account.access_token as string)
      }

      await sql`
        update sync_queue set status = 'done', updated_at = now(), last_error = null
        where id = ${row.id}
      `
      processed++
    } catch (e: unknown) {
      const message = e instanceof Error ? e.message : String(e)
      await sql`
        update sync_queue
        set status = 'failed',
            retry_count = retry_count + 1,
            last_error = ${message},
            updated_at = now()
        where id = ${row.id}
      `
      failed++
    }
  }

  return NextResponse.json({ processed, failed })
}
