'use client'

import { useMemo, useState } from 'react'
import { LANGUAGES } from '@/lib/languages'
import { generateTemplateDraft } from '@/lib/script-templates'
import { formatStackContext, type ProjectStack } from '@/lib/project-stack'
import { getAIWorker, useOfflineAIReady } from '@/lib/offline-ai'
import { copyToClipboard, downloadTextFile } from '@/lib/downloads'
import { enqueueSyncItem } from '@/lib/sync-queue'

type Props = { stack: ProjectStack; repoFullName?: string; onScriptSaved?: () => void }

type GenerationResult = { filename: string; content: string; notes: string[] }

export function ScriptGeneratorPanel({ stack, repoFullName, onScriptSaved }: Props) {
  const [languageId, setLanguageId] = useState('python')
  const [prompt, setPrompt] = useState('')
  const [mode, setMode] = useState<'offline' | 'online'>('offline')
  const [result, setResult] = useState<GenerationResult | null>(null)
  const [generating, setGenerating] = useState(false)
  const [saving, setSaving] = useState(false)
  const [saved, setSaved] = useState(false)
  const [queueing, setQueueing] = useState(false)
  const [queued, setQueued] = useState(false)

  const offlineReady = useOfflineAIReady()

  const language = useMemo(
    () => LANGUAGES.find(x => x.id === languageId) ?? LANGUAGES[0],
    [languageId]
  )

  async function onGenerate() {
    if (!prompt.trim()) return
    setGenerating(true)
    setResult(null)
    setSaved(false)
    setQueued(false)

    try {
      if (mode === 'offline') {
        const worker = offlineReady && language.offlineCapable ? getAIWorker() : null

        if (worker) {
          const id = crypto.randomUUID()
          await new Promise<void>(resolve => {
            const handler = (e: MessageEvent) => {
              if (e.data?.type === 'generated' && e.data.id === id) {
                setResult({
                  filename: `generated${language.fileExtensions[0] ?? '.txt'}`,
                  content: e.data.text,
                  notes: ['Generated offline using the cached model.'],
                })
                worker.removeEventListener('message', handler)
                resolve()
              }
            }
            worker.addEventListener('message', handler)
            worker.postMessage({
              type: 'generate',
              id,
              payload: { prompt, language: language.name, stackSummary: formatStackContext(stack) },
            })
          })
        } else {
          setResult(generateTemplateDraft({ language, prompt, stack, mode: 'offline' }))
        }
        return
      }

      const res = await fetch('/api/scripts/generate', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ languageId: language.id, prompt, stack }),
      })
      const data = await res.json()
      setResult(data)
    } finally {
      setGenerating(false)
    }
  }

  async function onSave() {
    if (!result) return
    setSaving(true)
    try {
      const res = await fetch('/api/generated-scripts', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          repoFullName: repoFullName ?? null,
          languageId: language.id,
          prompt,
          stackContext: stack,
          mode,
          filenameSuggestion: result.filename,
          content: result.content,
        }),
      })
      if (res.ok) {
        setSaved(true)
        onScriptSaved?.()
      }
    } finally {
      setSaving(false)
    }
  }

  async function onQueuePR() {
    if (!result || !repoFullName) return
    setQueueing(true)
    try {
      await enqueueSyncItem({
        repoFullName,
        mutationType: 'create_pr',
        payload: {
          repo: repoFullName,
          title: `chore: add generated script ${result.filename}`,
          body: `Generated by build.cc script generator.\n\n\`\`\`\n${result.content.slice(0, 500)}\n\`\`\``,
          head: 'build-cc/generated-scripts',
          base: 'main',
        },
      })
      setQueued(true)
    } finally {
      setQueueing(false)
    }
  }

  return (
    <div className="space-y-3">
      <div className="grid gap-2 sm:grid-cols-3">
        <select
          className="rounded border border-gray-700 bg-gray-900 px-3 py-2 text-xs font-mono text-white focus:outline-none"
          value={languageId}
          onChange={e => setLanguageId(e.target.value)}
        >
          {LANGUAGES.map(lang => (
            <option key={lang.id} value={lang.id}>{lang.name}</option>
          ))}
        </select>

        <select
          className="rounded border border-gray-700 bg-gray-900 px-3 py-2 text-xs font-mono text-white focus:outline-none"
          value={mode}
          onChange={e => setMode(e.target.value as 'offline' | 'online')}
        >
          <option value="offline" disabled={!language.offlineCapable}>
            {offlineReady && language.offlineCapable ? 'Offline (model ready)' : 'Offline draft (template)'}
          </option>
          <option value="online">Online enhanced</option>
        </select>

        <button
          onClick={onGenerate}
          disabled={generating || !prompt.trim()}
          className="rounded border border-emerald-600 px-3 py-2 text-xs font-mono text-emerald-400 hover:bg-emerald-500/10 disabled:opacity-40 disabled:cursor-not-allowed transition-colors"
        >
          {generating ? 'generating…' : '✦ generate'}
        </button>
      </div>

      <textarea
        className="w-full min-h-[80px] rounded border border-gray-700 bg-gray-900 px-3 py-2 text-xs font-mono text-white placeholder-gray-600 focus:outline-none resize-none"
        placeholder="Describe the script you want…"
        value={prompt}
        onChange={e => setPrompt(e.target.value)}
      />

      <div className="rounded border border-gray-800 bg-gray-900/30 px-3 py-2.5 space-y-1.5">
        <div className="text-[9px] font-mono text-gray-600 uppercase tracking-wider mb-1">prompt guide</div>
        {([
          { label: 'Role & Goal', desc: 'State what the script is or who the AI is mimicking.' },
          { label: 'Inputs', desc: 'Define what data enters the system.' },
          { label: 'Process', desc: 'List the step-by-step logic sequentially.' },
          { label: 'Outputs & Constraints', desc: 'Specify what the final result should look like.' },
        ] as const).map(({ label, desc }) => (
          <div key={label} className="flex gap-2 text-[10px] font-mono">
            <span className="text-gray-400 font-semibold flex-shrink-0">{label}:</span>
            <span className="text-gray-600">{desc}</span>
          </div>
        ))}
      </div>

      {result && (
        <div className="rounded border border-gray-700 bg-gray-900/50">
          <div className="flex items-center justify-between px-3 py-2 border-b border-gray-700">
            <span className="text-[10px] font-mono text-gray-500">{result.filename}</span>
            <div className="flex gap-2 flex-wrap justify-end">
              <button
                onClick={() => downloadTextFile(result.filename, result.content)}
                className="text-[10px] font-mono px-2 py-0.5 rounded border border-emerald-600 text-emerald-400 hover:bg-emerald-500/10 transition-colors"
              >
                ↓ download
              </button>
              <button
                onClick={() => copyToClipboard(result.content)}
                className="text-[10px] font-mono px-2 py-0.5 rounded border border-gray-600 text-gray-400 hover:bg-gray-700 transition-colors"
              >
                ⎘ copy
              </button>
              <button
                onClick={onSave}
                disabled={saving || saved}
                className="text-[10px] font-mono px-2 py-0.5 rounded border border-violet-700 text-violet-400 hover:bg-violet-500/10 disabled:opacity-40 disabled:cursor-not-allowed transition-colors"
              >
                {saved ? '✓ saved' : saving ? 'saving…' : '⊕ save'}
              </button>
              {repoFullName && (
                <button
                  onClick={onQueuePR}
                  disabled={queueing || queued}
                  className="text-[10px] font-mono px-2 py-0.5 rounded border border-amber-700 text-amber-400 hover:bg-amber-500/10 disabled:opacity-40 disabled:cursor-not-allowed transition-colors"
                >
                  {queued ? '✓ queued' : queueing ? 'queueing…' : '⇡ queue PR'}
                </button>
              )}
            </div>
          </div>
          <pre className="overflow-x-auto px-3 py-2 text-[11px] text-gray-300 leading-relaxed whitespace-pre-wrap">{result.content}</pre>
          {result.notes.length > 0 && (
            <ul className="px-3 py-2 border-t border-gray-700 space-y-0.5">
              {result.notes.map(note => (
                <li key={note} className="text-[10px] font-mono text-gray-600">↳ {note}</li>
              ))}
            </ul>
          )}
        </div>
      )}
    </div>
  )
}
